

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 384)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 201, 121))
        self.groupBox.setObjectName("groupBox")
        self.sbPortCom = QtWidgets.QSpinBox(self.groupBox)
        self.sbPortCom.setGeometry(QtCore.QRect(60, 20, 42, 22))
        self.sbPortCom.setProperty("value", 1)
        self.sbPortCom.setObjectName("sbPortCom")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 31, 16))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.label_5.setObjectName("label_5")
        self.cmSpeedCom = QtWidgets.QComboBox(self.groupBox)
        self.cmSpeedCom.setGeometry(QtCore.QRect(60, 50, 69, 22))
        self.cmSpeedCom.setObjectName("cmSpeedCom")
        self.cmSpeedCom.addItem("")
        self.cmSpeedCom.addItem("")
        self.cmSpeedCom.addItem("")
        self.cmSpeedCom.addItem("")
        self.sbAdrCom = QtWidgets.QSpinBox(self.groupBox)
        self.sbAdrCom.setGeometry(QtCore.QRect(60, 80, 42, 22))
        self.sbAdrCom.setProperty("value", 1)
        self.sbAdrCom.setRange(1, 254)
        self.sbAdrCom.setObjectName("sbAdrCom")
        self.ch643 = QtWidgets.QCheckBox(self.groupBox)
        self.ch643.setGeometry(QtCore.QRect(140, 90, 51, 17))
        self.ch643.setObjectName("ch643")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(220, 0, 211, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.entIpadr = QtWidgets.QLineEdit(self.groupBox_2)
        self.entIpadr.setGeometry(QtCore.QRect(90, 20, 113, 20))
        self.entIpadr.setObjectName("entIpadr")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 61, 16))
        self.label_2.setObjectName("label_2")
        self.entPortIp = QtWidgets.QLineEdit(self.groupBox_2)
        self.entPortIp.setGeometry(QtCore.QRect(90, 50, 61, 20))
        self.entPortIp.setObjectName("entPortIp")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(50, 50, 31, 16))
        self.label_3.setObjectName("label_3")
        self.chIPterm = QtWidgets.QCheckBox(self.groupBox_2)
        self.chIPterm.setGeometry(QtCore.QRect(10, 110, 121, 17))
        self.chIPterm.setObjectName("chIPterm")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(40, 80, 41, 16))
        self.label_8.setObjectName("label_8")
        self.entAdrTerIP = QtWidgets.QSpinBox(self.groupBox_2)
        self.entAdrTerIP.setGeometry(QtCore.QRect(90, 80, 42, 22))
        self.entAdrTerIP.setProperty("value", 1)
        self.entAdrTerIP.setRange(1, 254)
        self.entAdrTerIP.setObjectName("entAdrTerIP")
        self.entCommand = QtWidgets.QLineEdit(self.centralwidget)
        self.entCommand.setGeometry(QtCore.QRect(70, 140, 51, 20))
        self.entCommand.setObjectName("entCommand")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 140, 51, 16))
        self.label_6.setObjectName("label_6")
        self.btnOpros = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpros.setGeometry(QtCore.QRect(130, 140, 101, 23))
        self.btnOpros.setObjectName("btnOpros")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 170, 451, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.teOtp = QtWidgets.QTextEdit(self.groupBox_3)
        self.teOtp.setGeometry(QtCore.QRect(10, 30, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.teOtp.setFont(font)
        self.teOtp.setObjectName("teOtp")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 270, 451, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.teOtv = QtWidgets.QTextEdit(self.groupBox_4)
        self.teOtv.setGeometry(QtCore.QRect(10, 30, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.teOtv.setFont(font)
        self.teOtv.setObjectName("teOtv")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(430, 0, 211, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 20, 191, 31))
        self.lcdNumber.setObjectName("lcdNumber")
        self.bntPuskOpr = QtWidgets.QPushButton(self.groupBox_5)
        self.bntPuskOpr.setGeometry(QtCore.QRect(10, 60, 75, 23))
        self.bntPuskOpr.setObjectName("bntPuskOpr")
        self.btnStopOpr = QtWidgets.QPushButton(self.groupBox_5)
        self.btnStopOpr.setGeometry(QtCore.QRect(120, 60, 75, 23))
        self.btnStopOpr.setObjectName("btnStopOpr")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(470, 110, 171, 261))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 91, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Настройки COM:"))
        self.label.setText(_translate("MainWindow", "Порт:"))
        self.label_4.setText(_translate("MainWindow", "Скорость:"))
        self.label_5.setText(_translate("MainWindow", "Адрес:"))
        self.cmSpeedCom.setItemText(0, _translate("MainWindow", "9600"))
        self.cmSpeedCom.setItemText(1, _translate("MainWindow", "19200"))
        self.cmSpeedCom.setItemText(2, _translate("MainWindow", "57600"))
        self.cmSpeedCom.setItemText(3, _translate("MainWindow", "115200"))
        self.ch643.setText(_translate("MainWindow", "6.43"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Настройки IP:"))
        self.entIpadr.setText(_translate("MainWindow", "192.168.0.50"))
        self.label_2.setText(_translate("MainWindow", "IP- address:"))
        self.entPortIp.setText(_translate("MainWindow", "4001"))
        self.label_3.setText(_translate("MainWindow", "Порт:"))
        self.chIPterm.setText(_translate("MainWindow", "Сетевой терминал"))
        self.label_8.setText(_translate("MainWindow", "Адрес:"))
        self.entCommand.setText(_translate("MainWindow", "C3"))
        self.label_6.setText(_translate("MainWindow", "Команда:"))
        self.btnOpros.setText(_translate("MainWindow", "Отправить"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Отправка:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Приём:"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Постоянный опрос"))
        self.bntPuskOpr.setText(_translate("MainWindow", "Пуск"))
        self.btnStopOpr.setText(_translate("MainWindow", "Стоп"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Основные команды:"))
        self.label_7.setText(_translate("MainWindow", "C3 - вес брутто"))
        self.label_9.setText(_translate("MainWindow", "C2 - вес НЕТТО"))
        self.label_10.setText(_translate("MainWindow", "С0 - обнуление"))
